steps:
  # Step 1: Checkout the code from GitHub
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/zeshansaid/DockerCacheTest']
  
  # Step 2: Change directory to the repository
  - name: 'gcr.io/cloud-builders/docker'
  # your-repo-directory
    dir: 'DockerCacheTest'
    args:
          - build
          - -t
          - gcr.io/stone-composite-436518-s3/docker-cache:$COMMIT_SHA
          - -t
          - gcr.io/stone-composite-436518-s3/docker-cache:latest
          - .


  # Step 3: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'docker-cache'
    args: ['push', 'gcr.io/stone-composite-436518-s3/docker-cache']

  
  
  # Step 4: Deploy the Docker image to Google Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'run'
      - 'deploy'
      - 'docker-cache'
      - '--image'
      - 'gcr.io/stone-composite-436518-s3/docker-cache:latest'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--quiet'
    timeout: 3600s
 
# Store images in Google Artifact Registry 

images:
  - gcr.io/stone-composite-436518-s3/docker-cache:$COMMIT_SHA
  - gcr.io/stone-composite-436518-s3/docker-cache:latest
timeout: '3600s'  # Adjust timeout as necessary
options:
  logging: CLOUD_LOGGING_ONLY